FROM golang:1.12 AS builder
ENV GO111MODULE on
WORKDIR /go/src/app
COPY . .
RUN go get -d -v ./... && \
  CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -o caddy

FROM microsoft/nanoserver:1803
LABEL maintainer "Lucas Lorentz <lucaslorentzlara@hotmail.com>"

EXPOSE 80 443 2015

COPY --from=builder /go/src/app/caddy "C:\\caddy.exe"

ENTRYPOINT ["C:\\caddy.exe"]
